language: python
python:
  - "3.6"  
install:
  - pip install -r requirements.txt
script:
  - python -c "import sys; print(sys.version, '\n', sys.prefix)";
  - pytest ./test/ --doctest-modules -v --cov ./ --cov-report html --cov-config .coveragerc

after_success:
  - echo == ALL TESTS PASSED ==
  - coveralls

after_failure:
  - echo == FAILURE ==
